server {
    listen 80;
    index index.html;
    root /var/www/html; # Raíz global del contenedor Nginx

    # 1. FRONTEND: Entra directo a la subcarpeta del frontend montada en Nginx
    location / {
        root /var/www/html/frontend;
        try_files $uri $uri/ /index.html;
    }

    # 2. BACKEND: Manda las peticiones de la API apuntando a la subcarpeta de Nginx
    location /api {
        try_files $uri $uri/ /backend/api/public/index.php?$query_string;
    }

    # 3. PROCESAMIENTO PHP: El traductor inteligente
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        
        fastcgi_pass laravel:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        
        # TRUCO MAESTRO: Aunque Nginx busque el archivo en /backend/api/public, 
        # le ordena al contenedor de Laravel ejecutar el index.php que está en su propia raíz.
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # 4. STORAGE: Mapear recursos directamente en Nginx sin depender del enlace simbólico
    location /storage {
        alias /var/www/html/backend/api/storage/app/public;
        try_files $uri =404;
    }

    # 5. WEBSOCKETS (Reverb): El proxy inverso para tiempo real
    location ~ ^/(app|apps)/ {
        # Apunta exactamente al nombre del contenedor de Reverb en tu docker-compose
        proxy_pass http://laravel-reverb:8080;
        proxy_http_version 1.1;
        
        # Cabeceras obligatorias para negociar el protocolo WebSocket
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        
        # Pasar el dominio real exacto que viene desde Cloudflare
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        
        # Evitar que Nginx cierre la conexión silenciosamente a los 60 segundos
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }

    # 6. SEGURIDAD: Bloquear acceso a archivos ocultos (.env, .git, etc.)
    location ~ /\.(?!well-known).* {
        deny all;
    }
}