server {
    listen 80;
    index index.html;
    root /var/www/html; # Raíz global del contenedor Nginx

    # 1. FRONTEND: Entra directo a la subcarpeta del frontend montada en Nginx
    location / {
        root /var/www/html/frontend;
        try_files $uri $uri/ /index.html;
    }

    # 2. BACKEND: Manda las peticiones de la API apuntando a la subcarpeta de Nginx
    location /api {
        try_files $uri $uri/ /backend/api/public/index.php?$query_string;
    }

    # 3. PROCESAMIENTO PHP: El traductor inteligente
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        
        fastcgi_pass laravel:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        
        # TRUCO MAESTRO: Aunque Nginx busque el archivo en /backend/api/public, 
        # le ordena al contenedor de Laravel ejecutar el index.php que está en su propia raíz.
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}