server {
    listen 80;
    index index.html;

    # 1. El root principal apunta a la raíz compartida de tus volúmenes
    root /var/www/html;

    # 2. FRONTEND: Entra directo a la subcarpeta del frontend
    location / {
        root /var/www/html/frontend;
        try_files $uri $uri/ /index.html;
    }

    # 3. BACKEND: Captura todo lo que vaya a /api y lo manda a Laravel
    location /api {
        # Reescribe la petición internamente para enviarla al index.php de Laravel
        try_files $uri $uri/ /backend/api/public/index.php?$query_string;
    }

    # 4. PROCESAMIENTO PHP: El bloque clave para que Docker y FastCGI se entiendan
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        
        # Conecta con el puerto 9000 del servicio php-fpm del contenedor 'laravel'
        fastcgi_pass laravel:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        
        fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}