# Identificador único del proyecto en SonarQube
sonar.projectKey=sistema-incidencias-sqa
sonar.projectName=Sistema Web de Gestión de Incidencias
sonar.projectVersion=1.0

# Directorios de código a analizar
sonar.sources=backend/api/app,frontend/js

# Exclusiones de archivos/carpetas de terceros para no sesgar las métricas
sonar.exclusions=**/vendor/**,**/node_modules/**,**/storage/**,**/public/**,**/*.spec.js,**/tests/**

# URL del servidor local de SonarQube
sonar.host.url=http://localhost:9000

# Codificación de caracteres
sonar.sourceEncoding=UTF-8
