tunnel: 72de7bd0-601b-4354-9def-08a03b539bdb
credentials-file: /home/nonroot/.cloudflared/72de7bd0-601b-4354-9def-08a03b539bdb.json

ingress:
  - hostname: alertcity.dihm-muertos.site
    service: http://nginx:80
  - service: http_status:404