name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed # Solo despliega cuando el PR es aprobado y cerrado/mezclado

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Apagar contenedores anteriores
        run: docker compose -f docker-compose.aws.yml down || true

      - name: Eliminar residuos bloqueados usando Docker
        run: |
          if [ -d "backend/api/vendor" ]; then
            docker run --rm -v $(pwd):/workspace busybox rm -rf /workspace/backend/api/vendor
          fi
          if [ -d "backend/api/build" ]; then
            docker run --rm -v $(pwd):/workspace busybox rm -rf /workspace/backend/api/build
          fi
          if [ -d "frontend/coverage" ]; then
            docker run --rm -v $(pwd):/workspace busybox rm -rf /workspace/frontend/coverage
          fi
          if [ -d "frontend/node_modules" ]; then
            docker run --rm -v $(pwd):/workspace busybox rm -rf /workspace/frontend/node_modules
          fi

      - name: Descargar el nuevo código
        uses: actions/checkout@v4

      - name: Configurar variables de entorno y Secretos
        env:
          ENV_AWS_SECRET: ${{ secrets.ENV_AWS }}
        run: |
          echo "$ENV_AWS_SECRET" > backend/api/.env
          echo "DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}" > .env
          echo "CLOUDFLARE_TUNNEL_TOKEN=${{ secrets.PROD_CLOUDFLARE_TUNNEL_TOKEN }}" >> .env
          echo "GRAFANA_ADMIN_PASSWORD=${{ secrets.PROD_GRAFANA_ADMIN_PASSWORD }}" >> .env
          echo "SONAR_DB_PASSWORD=${{ secrets.PROD_SONAR_DB_PASSWORD }}" >> .env
          
          # Preparar archivo de cloudflare
          cp cloudflare/config.aws.yml cloudflare/config.yml

      - name: Reconstruir y levantar contenedores en Producción
        run: |
          docker compose -f docker-compose.aws.yml pull
          docker compose -f docker-compose.aws.yml up -d --build
          docker image prune -f
