# 1. EL DETONANTE: Cuándo se debe activar
on:
  push:
    branches: [ "develop" ]

# 2. EL LUGAR: Dónde se va a ejecutar (¡Tu VAIO!)
jobs:
  laravel-tests:
    runs-on: self-hosted

    # 3. LOS PASOS: Usando el PHP nativo de tu servidor
    steps:
    - name: Copiar el código a la VAIO
      uses: actions/checkout@v4
    
    - name: Instalar dependencias de Laravel (Composer)
      run: composer install --no-ansi --no-interaction --no-progress

    - name: Copiar archivo de entorno (.env)
      run: cp .env.example .env

    - name: Generar clave de seguridad de Laravel
      run: php artisan key:generate

    - name: Ejecutar pruebas automatizadas
      run: php artisan test
